import type { Review } from '@/types';

export const reviews: Review[] = [
  {
    id: '1',
    platform: 'Android',
    author: 'Rohan S.',
    rating: 1,
    text: 'App crashes every time I try to login. Completely unusable.',
    date: '2024-07-20',
    sentiment: 'Negative',
    theme: 'Crash',
  },
  {
    id: '2',
    platform: 'iOS',
    author: 'Priya M.',
    rating: 5,
    text: 'The new UPI feature is seamless! So much faster than other apps.',
    date: '2024-07-19',
    sentiment: 'Positive',
    theme: 'UPI',
  },
  {
    id: '3',
    platform: 'Android',
    author: 'Amit K.',
    rating: 2,
    text: 'Registration process is a nightmare. It keeps asking for the same documents.',
    date: '2024-07-18',
    sentiment: 'Negative',
    theme: 'Registration',
  },
  {
    id: '4',
    platform: 'iOS',
    author: 'Sneha P.',
    rating: 4,
    text: 'I like the credit card management section. Very clear and easy to track expenses.',
    date: '2024-07-18',
    sentiment: 'Positive',
    theme: 'Credit Card',
  },
  {
    id: '5',
    platform: 'Android',
    author: 'Vikram R.',
    rating: 1,
    text: 'Login is a pain. Face ID rarely works and I have to enter my PIN every single time.',
    date: '2024-07-17',
    sentiment: 'Negative',
    theme: 'Login',
  },
  {
    id: '6',
    platform: 'iOS',
    author: 'Anjali D.',
    rating: 3,
    text: 'The app is okay, but I am concerned about the number of permissions it asks for.',
    date: '2024-07-16',
    sentiment: 'Neutral',
    theme: 'Privacy',
  },
  {
    id: '7',
    platform: 'Android',
    author: 'Sandeep G.',
    rating: 5,
    text: 'Great app! Everything works as expected. Very reliable for my daily transactions.',
    date: '2024-07-15',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '8',
    platform: 'iOS',
    author: 'Kavita N.',
    rating: 2,
    text: 'UPI payments fail frequently, especially during peak hours. Very frustrating.',
    date: '2024-07-14',
    sentiment: 'Negative',
    theme: 'UPI',
  },
  {
    id: '9',
    platform: 'Android',
    author: 'Manish T.',
    rating: 4,
    text: 'The app has improved a lot over the last few months. Fewer crashes now.',
    date: '2024-07-12',
    sentiment: 'Positive',
    theme: 'Crash',
  },
  {
    id: '10',
    platform: 'iOS',
    author: 'Divya C.',
    rating: 3,
    text: 'The user interface feels a bit dated compared to other banking apps.',
    date: '2024-07-11',
    sentiment: 'Neutral',
    theme: 'General',
  },
  {
    id: '11',
    platform: 'Android',
    author: 'Rajesh P.',
    rating: 1,
    text: 'I can\'t even get past the login screen. It says "Invalid credentials" even though they are correct.',
    date: '2024-06-30',
    sentiment: 'Negative',
    theme: 'Login',
  },
  {
    id: '12',
    platform: 'iOS',
    author: 'Sunita V.',
    rating: 5,
    text: 'The security features are top-notch. I feel my data is safe.',
    date: '2024-06-28',
    sentiment: 'Positive',
    theme: 'Privacy',
  },
  {
    id: '13',
    platform: 'Android',
    author: 'Karan L.',
    rating: 2,
    text: 'Applying for a new credit card through the app was a buggy experience.',
    date: '2024-06-25',
    sentiment: 'Negative',
    theme: 'Credit Card',
  },
  {
    id: '14',
    platform: 'iOS',
    author: 'Neha B.',
    rating: 4,
    text: 'Customer support through the app chat is surprisingly quick and helpful.',
    date: '2024-06-22',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '15',
    platform: 'Android',
    author: 'Arjun M.',
    rating: 1,
    text: 'The app crashed and I was debited twice for a single transaction. Terrible!',
    date: '2024-06-20',
    sentiment: 'Negative',
    theme: 'Crash',
  },
];
