import type { Review } from '@/types';

export const reviews: Review[] = [
  {
    id: '1',
    platform: 'Android',
    author: 'Rohan S.',
    rating: 1,
    text: 'App crashes every time I try to login. Completely unusable since the last update.',
    date: '2024-07-20',
    sentiment: 'Negative',
    theme: 'Crash',
  },
  {
    id: '2',
    platform: 'iOS',
    author: 'Priya M.',
    rating: 5,
    text: 'The new UPI feature is seamless! So much faster than other apps. QR code scanning is instant.',
    date: '2024-07-19',
    sentiment: 'Positive',
    theme: 'UPI',
  },
  {
    id: '3',
    platform: 'Android',
    author: 'Amit K.',
    rating: 2,
    text: 'Registration process is a nightmare. It keeps asking for the same documents and then fails at the last step.',
    date: '2024-07-18',
    sentiment: 'Negative',
    theme: 'Registration',
  },
  {
    id: '4',
    platform: 'iOS',
    author: 'Sneha P.',
    rating: 4,
    text: 'I like the credit card management section. Very clear and easy to track expenses and pay bills.',
    date: '2024-07-18',
    sentiment: 'Positive',
    theme: 'Credit Card',
  },
  {
    id: '5',
    platform: 'Android',
    author: 'Vikram R.',
    rating: 1,
    text: 'Login is a pain. Face ID rarely works and I have to enter my PIN every single time. Please fix this.',
    date: '2024-07-17',
    sentiment: 'Negative',
    theme: 'Login',
  },
  {
    id: '6',
    platform: 'iOS',
    author: 'Anjali D.',
    rating: 3,
    text: 'The app is okay, but I am concerned about the number of permissions it asks for. Seems excessive for a banking app.',
    date: '2024-07-16',
    sentiment: 'Neutral',
    theme: 'Privacy',
  },
  {
    id: '7',
    platform: 'Android',
    author: 'Sandeep G.',
    rating: 5,
    text: 'Great app! Everything works as expected. Very reliable for my daily transactions and fund transfers.',
    date: '2024-07-15',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '8',
    platform: 'iOS',
    author: 'Kavita N.',
    rating: 2,
    text: 'UPI payments fail frequently, especially during peak hours. Error messages are not helpful.',
    date: '2024-07-14',
    sentiment: 'Negative',
    theme: 'UPI',
  },
  {
    id: '9',
    platform: 'Android',
    author: 'Manish T.',
    rating: 4,
    text: 'The app has improved a lot over the last few months. Fewer crashes now and the UI feels smoother.',
    date: '2024-07-12',
    sentiment: 'Positive',
    theme: 'Crash',
  },
  {
    id: '10',
    platform: 'iOS',
    author: 'Divya C.',
    rating: 3,
    text: 'The user interface feels a bit dated compared to other banking apps like ICICI or Axis.',
    date: '2024-07-11',
    sentiment: 'Neutral',
    theme: 'General',
  },
  {
    id: '11',
    platform: 'Android',
    author: 'Rajesh P.',
    rating: 1,
    text: 'I can\'t even get past the login screen. It says "Invalid credentials" even though they are correct. Resetting password doesn\'t help.',
    date: '2024-06-30',
    sentiment: 'Negative',
    theme: 'Login',
  },
  {
    id: '12',
    platform: 'iOS',
    author: 'Sunita V.',
    rating: 5,
    text: 'The security features are top-notch. I feel my data is safe with features like Secure Access.',
    date: '2024-06-28',
    sentiment: 'Positive',
    theme: 'Privacy',
  },
  {
    id: '13',
    platform: 'Android',
    author: 'Karan L.',
    rating: 2,
    text: 'Applying for a new credit card through the app was a buggy experience. The form kept resetting.',
    date: '2024-06-25',
    sentiment: 'Negative',
    theme: 'Credit Card',
  },
  {
    id: '14',
    platform: 'iOS',
    author: 'Neha B.',
    rating: 4,
    text: 'Customer support through the app chat is surprisingly quick and helpful. Got my issue resolved in minutes.',
    date: '2024-06-22',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '15',
    platform: 'Android',
    author: 'Arjun M.',
    rating: 1,
    text: 'The app crashed and I was debited twice for a single transaction. Support is not responding!',
    date: '2024-06-20',
    sentiment: 'Negative',
    theme: 'Crash',
  },
  {
    id: '16',
    platform: 'iOS',
    author: 'Meera J.',
    rating: 5,
    text: 'Bill Pay feature is a lifesaver. So easy to manage all my utility bills in one place.',
    date: '2024-06-18',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '17',
    platform: 'Android',
    author: 'Harish V.',
    rating: 2,
    text: 'The app is so slow. Every tap takes seconds to respond. My phone is new, so it\'s the app.',
    date: '2024-06-15',
    sentiment: 'Negative',
    theme: 'General',
  },
  {
    id: '18',
    platform: 'iOS',
    author: 'Geeta K.',
    rating: 1,
    text: 'I tried to register for the app but it says my mobile number is not linked to my account, but it is! Useless.',
    date: '2024-06-14',
    sentiment: 'Negative',
    theme: 'Registration',
  },
  {
    id: '19',
    platform: 'Android',
    author: 'Suresh R.',
    rating: 4,
    text: 'The fixed deposit booking process is very intuitive and simple. Well done.',
    date: '2024-06-10',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '20',
    platform: 'iOS',
    author: 'Tina S.',
    rating: 2,
    text: 'Why does the app log me out so frequently? It\'s very annoying to log back in every 5 minutes.',
    date: '2024-06-05',
    sentiment: 'Negative',
    theme: 'Login',
  },
  {
    id: '21',
    platform: 'Android',
    author: 'Ankit G.',
    rating: 4,
    text: 'Good to see transaction history is detailed and easy to filter.',
    date: '2024-07-21',
    sentiment: 'Positive',
    theme: 'General',
  },
  {
    id: '22',
    platform: 'iOS',
    author: 'Vijay P.',
    rating: 1,
    text: 'The app keeps crashing on my iPhone 14 Pro. I have to use the website instead.',
    date: '2024-07-21',
    sentiment: 'Negative',
    theme: 'Crash',
  },
  {
    id: '23',
    platform: 'Android',
    author: 'Pooja B.',
    rating: 5,
    text: 'UPI payments are incredibly fast. I switched from GPay to this for most of my payments.',
    date: '2024-07-22',
    sentiment: 'Positive',
    theme: 'UPI',
  },
  {
    id: '24',
    platform: 'iOS',
    author: 'Nisha S.',
    rating: 2,
    text: 'Updating my address was impossible through the app. The form kept giving a vague "error".',
    date: '2024-07-22',
    sentiment: 'Negative',
    theme: 'General',
  },
  {
    id: '25',
    platform: 'Android',
    author: 'Manoj K.',
    rating: 3,
    text: 'It works, but the design feels old. Needs a modern refresh.',
    date: '2024-07-23',
    sentiment: 'Neutral',
    theme: 'General',
  },
  {
    id: '26',
    platform: 'iOS',
    author: 'Sarita R.',
    rating: 1,
    text: 'Fingerprint login stopped working after the iOS 17 update. Very inconvenient.',
    date: '2024-07-23',
    sentiment: 'Negative',
    theme: 'Login',
  },
  {
    id: '27',
    platform: 'Android',
    author: 'Deepak C.',
    rating: 4,
    text: 'I appreciate the detailed alerts for every transaction. Helps me keep track of my spending.',
    date: '2024-07-24',
    sentiment: 'Positive',
    theme: 'Privacy',
  },
  {
    id: '28',
    platform: 'iOS',
    author: 'Ravi V.',
    rating: 2,
    text: 'Credit card rewards points are not updating correctly in the app.',
    date: '2024-07-24',
    sentiment: 'Negative',
    theme: 'Credit Card',
  },
];
